
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action HomeAction;
	
	private global::Gtk.Action testAction;
	
	private global::Gtk.Action testAction1;
	
	private global::Gtk.Action SignAndVerifyTestAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Button btnTest;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Label lblOne;
	
	private global::Gtk.Label GtkLabel2;
	
	private global::Gtk.Label lblTwo;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.HomeAction = new global::Gtk.Action ("HomeAction", global::Mono.Unix.Catalog.GetString ("Home"), null, null);
		this.HomeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Home");
		w1.Add (this.HomeAction, null);
		this.testAction = new global::Gtk.Action ("testAction", global::Mono.Unix.Catalog.GetString ("test"), null, null);
		this.testAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("test");
		w1.Add (this.testAction, null);
		this.testAction1 = new global::Gtk.Action ("testAction1", global::Mono.Unix.Catalog.GetString ("test"), null, null);
		this.testAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("test");
		w1.Add (this.testAction1, null);
		this.SignAndVerifyTestAction = new global::Gtk.Action ("SignAndVerifyTestAction", global::Mono.Unix.Catalog.GetString ("SignAndVerifyTest"), null, null);
		this.SignAndVerifyTestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("SignAndVerifyTest");
		w1.Add (this.SignAndVerifyTestAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='HomeAction' action='HomeAction'><menuitem name='testAction1' action='testAction1'/></menu><menu name='testAction' action='testAction'><menuitem name='SignAndVerifyTestAction' action='SignAndVerifyTestAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnTest = new global::Gtk.Button ();
		this.btnTest.CanFocus = true;
		this.btnTest.Name = "btnTest";
		this.btnTest.UseUnderline = true;
		this.btnTest.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox1.Add (this.btnTest);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnTest]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.lblOne = new global::Gtk.Label ();
		this.lblOne.Name = "lblOne";
		this.lblOne.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.GtkAlignment.Add (this.lblOne);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.hbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblTwo = new global::Gtk.Label ();
		this.lblTwo.Name = "lblTwo";
		this.lblTwo.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
		this.hbox1.Add (this.lblTwo);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblTwo]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 677;
		this.DefaultHeight = 468;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SignAndVerifyTestAction.Activated += new global::System.EventHandler (this.menuSignAndVerify_clicked);
		this.btnTest.Clicked += new global::System.EventHandler (this.btnTest_Clicked);
	}
}
