
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class VerticalMenu
	{
		private global::Gtk.VBox vboxContainer;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.VerticalMenu
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.VerticalMenu";
			// Container child Wallet.VerticalMenu.Gtk.Container+ContainerChild
			this.vboxContainer = new global::Gtk.VBox();
			this.vboxContainer.Name = "vboxContainer";
			this.vboxContainer.Homogeneous = true;
			this.Add(this.vboxContainer);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
