
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet.Widgets.Log
{
	public partial class LogTotals
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label5;

		private global::Gtk.Label labelReceived;

		private global::Gtk.EventBox eventbox2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label7;

		private global::Gtk.Label labelSent;

		private global::Gtk.EventBox eventbox3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelBalance;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Widgets.Log.LogTotals
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Widgets.Log.LogTotals";
			// Container child Wallet.Widgets.Log.LogTotals.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.BorderWidth = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = true;
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(10));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xpad = 8;
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("TOTAL RECEIVED:");
			this.vbox1.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelReceived = new global::Gtk.Label();
			this.labelReceived.Name = "labelReceived";
			this.labelReceived.Xpad = 8;
			this.labelReceived.Xalign = 0F;
			this.labelReceived.LabelProp = global::Mono.Unix.Catalog.GetString("Received");
			this.vbox1.Add(this.labelReceived);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelReceived]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.eventbox1.Add(this.vbox1);
			this.hbox1.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox1]));
			w4.Position = 0;
			w4.Padding = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(10));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xpad = 8;
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("TOTAL SENT:");
			this.vbox2.Add(this.label7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label7]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelSent = new global::Gtk.Label();
			this.labelSent.Name = "labelSent";
			this.labelSent.Xpad = 8;
			this.labelSent.Xalign = 0F;
			this.labelSent.LabelProp = global::Mono.Unix.Catalog.GetString("Sent");
			this.vbox2.Add(this.labelSent);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelSent]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.eventbox2.Add(this.vbox2);
			this.hbox1.Add(this.eventbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox2]));
			w8.Position = 1;
			w8.Padding = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox3 = new global::Gtk.EventBox();
			this.eventbox3.Name = "eventbox3";
			// Container child eventbox3.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xpad = 8;
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("TOTAL BALANCE:");
			this.vbox3.Add(this.label9);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label9]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelBalance = new global::Gtk.Label();
			this.labelBalance.Name = "labelBalance";
			this.labelBalance.Xpad = 8;
			this.labelBalance.Xalign = 0F;
			this.labelBalance.LabelProp = global::Mono.Unix.Catalog.GetString("Balance");
			this.vbox3.Add(this.labelBalance);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.labelBalance]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.eventbox3.Add(this.vbox3);
			this.hbox1.Add(this.eventbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox3]));
			w12.Position = 2;
			w12.Padding = ((uint)(5));
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
