
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class SendDialogStep1
	{
		private global::Gtk.VBox vbox2;

		private global::Wallet.DialogField dialogfieldTo;

		private global::Wallet.DialogField dialogfieldAmount;

		private global::Wallet.DialogComboField dialogcombofieldAsset;

		private global::Gtk.Label labelMessage;

		private global::Gtk.HBox hbox4;

		private global::Gtk.EventBox eventboxSend;

		private global::Gtk.Image image1;

		private global::Gtk.Button buttonRaw;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.SendDialogStep1
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.SendDialogStep1";
			// Container child Wallet.SendDialogStep1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.dialogfieldTo = new global::Wallet.DialogField();
			this.dialogfieldTo.Events = ((global::Gdk.EventMask)(256));
			this.dialogfieldTo.Name = "dialogfieldTo";
			this.dialogfieldTo.Value = "";
			this.vbox2.Add(this.dialogfieldTo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.dialogfieldTo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.dialogfieldAmount = new global::Wallet.DialogField();
			this.dialogfieldAmount.Events = ((global::Gdk.EventMask)(256));
			this.dialogfieldAmount.Name = "dialogfieldAmount";
			this.vbox2.Add(this.dialogfieldAmount);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.dialogfieldAmount]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.dialogcombofieldAsset = new global::Wallet.DialogComboField();
			this.dialogcombofieldAsset.Events = ((global::Gdk.EventMask)(256));
			this.dialogcombofieldAsset.Name = "dialogcombofieldAsset";
			this.vbox2.Add(this.dialogcombofieldAsset);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.dialogcombofieldAsset]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelMessage = new global::Gtk.Label();
			this.labelMessage.Name = "labelMessage";
			this.vbox2.Add(this.labelMessage);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelMessage]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventboxSend = new global::Gtk.EventBox();
			this.eventboxSend.Name = "eventboxSend";
			this.eventboxSend.VisibleWindow = false;
			// Container child eventboxSend.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.send_dialog.png");
			this.eventboxSend.Add(this.image1);
			this.hbox4.Add(this.eventboxSend);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventboxSend]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonRaw = new global::Gtk.Button();
			this.buttonRaw.CanFocus = true;
			this.buttonRaw.Name = "buttonRaw";
			this.buttonRaw.UseUnderline = true;
			this.buttonRaw.Label = global::Mono.Unix.Catalog.GetString("Raw");
			this.hbox4.Add(this.buttonRaw);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonRaw]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
