
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class WidgetMyButton
	{
		private global::Gtk.EventBox eventbox9;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.HBox hbox7;
		
		private global::Wallet.WidgetButtonContent widgetbuttoncontent1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.WidgetMyButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Wallet.WidgetMyButton";
			// Container child Wallet.WidgetMyButton.Gtk.Container+ContainerChild
			this.eventbox9 = new global::Gtk.EventBox ();
			this.eventbox9.Name = "eventbox9";
			// Container child eventbox9.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Homogeneous = true;
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.HeightRequest = 100;
			this.hbox7.Name = "hbox7";
			this.hbox7.Homogeneous = true;
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.widgetbuttoncontent1 = new global::Wallet.WidgetButtonContent ();
			this.widgetbuttoncontent1.Events = ((global::Gdk.EventMask)(256));
			this.widgetbuttoncontent1.Name = "widgetbuttoncontent1";
			this.hbox7.Add (this.widgetbuttoncontent1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.widgetbuttoncontent1]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox9.Add (this.hbox7);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox7]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.eventbox9.Add (this.vbox9);
			this.Add (this.eventbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
