
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class WalletSendLayout
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hboxTop;

		private global::Gtk.Label label5;

		private global::Gtk.Button buttonBack;

		private global::Gtk.VBox vboxMainInner;

		private global::Gtk.EventBox eventboxDestination;

		private global::Gtk.VBox vboxDestination;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label labelDestination;

		private global::Gtk.Label labelDestinationError;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry entryDestination;

		private global::Gtk.Button buttonPaste;

		private global::Gtk.EventBox eventboxAsset;

		private global::Gtk.VBox vboxDestination1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label labelAsset;

		private global::Gtk.HBox hboxAsset;

		private global::Gtk.EventBox eventbox6;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Image imageAsset;

		private global::Gtk.Label labelSelectedAsset;

		private global::Gtk.Label labelSelectOtherAsset;

		private global::Gtk.ComboBox comboboxAsset;

		private global::Gtk.EventBox eventboxAmount;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label labelAmount;

		private global::Gtk.Entry entryAmount;

		private global::Gtk.Label labelSelectedAsset1;

		private global::Gtk.Label labelAmountError;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label labelBalance;

		private global::Gtk.Label labelBalanceValue;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button buttonSignAndReview;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.WalletSendLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.WalletSendLayout";
			// Container child Wallet.WalletSendLayout.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hboxTop = new global::Gtk.HBox();
			this.hboxTop.Name = "hboxTop";
			this.hboxTop.Spacing = 6;
			this.hboxTop.BorderWidth = ((uint)(10));
			// Container child hboxTop.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.hboxTop.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxTop[this.label5]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child hboxTop.Gtk.Box+BoxChild
			this.buttonBack = new global::Gtk.Button();
			this.buttonBack.CanFocus = true;
			this.buttonBack.Name = "buttonBack";
			this.buttonBack.UseUnderline = true;
			this.buttonBack.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.hboxTop.Add(this.buttonBack);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxTop[this.buttonBack]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox3.Add(this.hboxTop);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hboxTop]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vboxMainInner = new global::Gtk.VBox();
			this.vboxMainInner.Name = "vboxMainInner";
			this.vboxMainInner.Spacing = 15;
			this.vboxMainInner.BorderWidth = ((uint)(40));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.eventboxDestination = new global::Gtk.EventBox();
			this.eventboxDestination.Name = "eventboxDestination";
			// Container child eventboxDestination.Gtk.Container+ContainerChild
			this.vboxDestination = new global::Gtk.VBox();
			this.vboxDestination.Name = "vboxDestination";
			this.vboxDestination.BorderWidth = ((uint)(5));
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.BorderWidth = ((uint)(10));
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelDestination = new global::Gtk.Label();
			this.labelDestination.Name = "labelDestination";
			this.labelDestination.LabelProp = global::Mono.Unix.Catalog.GetString("Destination:");
			this.hbox2.Add(this.labelDestination);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.labelDestination]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(10));
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelDestinationError = new global::Gtk.Label();
			this.labelDestinationError.Name = "labelDestinationError";
			this.hbox2.Add(this.labelDestinationError);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.labelDestinationError]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vboxDestination.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.hbox2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.BorderWidth = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryDestination = new global::Gtk.Entry();
			this.entryDestination.CanFocus = true;
			this.entryDestination.Name = "entryDestination";
			this.entryDestination.IsEditable = true;
			this.entryDestination.InvisibleChar = '●';
			this.hbox1.Add(this.entryDestination);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryDestination]));
			w7.Position = 0;
			w7.Padding = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonPaste = new global::Gtk.Button();
			this.buttonPaste.CanFocus = true;
			this.buttonPaste.Name = "buttonPaste";
			this.buttonPaste.UseUnderline = true;
			this.buttonPaste.BorderWidth = ((uint)(5));
			this.buttonPaste.Label = global::Mono.Unix.Catalog.GetString("Paste");
			this.hbox1.Add(this.buttonPaste);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonPaste]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vboxDestination.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.eventboxDestination.Add(this.vboxDestination);
			this.vboxMainInner.Add(this.eventboxDestination);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.eventboxDestination]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(5));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.eventboxAsset = new global::Gtk.EventBox();
			this.eventboxAsset.Name = "eventboxAsset";
			// Container child eventboxAsset.Gtk.Container+ContainerChild
			this.vboxDestination1 = new global::Gtk.VBox();
			this.vboxDestination1.Name = "vboxDestination1";
			this.vboxDestination1.BorderWidth = ((uint)(5));
			// Container child vboxDestination1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.BorderWidth = ((uint)(10));
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelAsset = new global::Gtk.Label();
			this.labelAsset.Name = "labelAsset";
			this.labelAsset.LabelProp = global::Mono.Unix.Catalog.GetString("Asset:");
			this.hbox3.Add(this.labelAsset);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelAsset]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			w12.Padding = ((uint)(10));
			this.vboxDestination1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxDestination1[this.hbox3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxDestination1.Gtk.Box+BoxChild
			this.hboxAsset = new global::Gtk.HBox();
			this.hboxAsset.Name = "hboxAsset";
			this.hboxAsset.BorderWidth = ((uint)(10));
			// Container child hboxAsset.Gtk.Box+BoxChild
			this.eventbox6 = new global::Gtk.EventBox();
			this.eventbox6.Name = "eventbox6";
			this.eventbox6.BorderWidth = ((uint)(10));
			// Container child eventbox6.Gtk.Container+ContainerChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.imageAsset = new global::Gtk.Image();
			this.imageAsset.Name = "imageAsset";
			this.imageAsset.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-connect", global::Gtk.IconSize.Menu);
			this.hbox7.Add(this.imageAsset);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.imageAsset]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelSelectedAsset = new global::Gtk.Label();
			this.labelSelectedAsset.Name = "labelSelectedAsset";
			this.labelSelectedAsset.LabelProp = global::Mono.Unix.Catalog.GetString("Zen");
			this.hbox7.Add(this.labelSelectedAsset);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.labelSelectedAsset]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.eventbox6.Add(this.hbox7);
			this.hboxAsset.Add(this.eventbox6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxAsset[this.eventbox6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hboxAsset.Gtk.Box+BoxChild
			this.labelSelectOtherAsset = new global::Gtk.Label();
			this.labelSelectOtherAsset.Name = "labelSelectOtherAsset";
			this.labelSelectOtherAsset.LabelProp = global::Mono.Unix.Catalog.GetString("or select other asset:");
			this.hboxAsset.Add(this.labelSelectOtherAsset);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxAsset[this.labelSelectOtherAsset]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(10));
			// Container child hboxAsset.Gtk.Box+BoxChild
			this.comboboxAsset = global::Gtk.ComboBox.NewText();
			this.comboboxAsset.Name = "comboboxAsset";
			this.hboxAsset.Add(this.comboboxAsset);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hboxAsset[this.comboboxAsset]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(10));
			this.vboxDestination1.Add(this.hboxAsset);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxDestination1[this.hboxAsset]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.eventboxAsset.Add(this.vboxDestination1);
			this.vboxMainInner.Add(this.eventboxAsset);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.eventboxAsset]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.eventboxAmount = new global::Gtk.EventBox();
			this.eventboxAmount.Name = "eventboxAmount";
			// Container child eventboxAmount.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 10;
			this.hbox6.BorderWidth = ((uint)(15));
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelAmount = new global::Gtk.Label();
			this.labelAmount.Name = "labelAmount";
			this.labelAmount.LabelProp = global::Mono.Unix.Catalog.GetString("Amount to send:");
			this.hbox6.Add(this.labelAmount);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelAmount]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(10));
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryAmount = new global::Gtk.Entry();
			this.entryAmount.CanFocus = true;
			this.entryAmount.Name = "entryAmount";
			this.entryAmount.IsEditable = true;
			this.entryAmount.InvisibleChar = '●';
			this.entryAmount.Xalign = 1F;
			this.hbox6.Add(this.entryAmount);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryAmount]));
			w24.Position = 1;
			w24.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelSelectedAsset1 = new global::Gtk.Label();
			this.labelSelectedAsset1.Name = "labelSelectedAsset1";
			this.labelSelectedAsset1.LabelProp = global::Mono.Unix.Catalog.GetString("Zen");
			this.hbox6.Add(this.labelSelectedAsset1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelSelectedAsset1]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelAmountError = new global::Gtk.Label();
			this.labelAmountError.Name = "labelAmountError";
			this.hbox6.Add(this.labelAmountError);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelAmountError]));
			w26.PackType = ((global::Gtk.PackType)(1));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox4.Add(this.hbox6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 10;
			this.hbox8.BorderWidth = ((uint)(15));
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelBalance = new global::Gtk.Label();
			this.labelBalance.Name = "labelBalance";
			this.labelBalance.LabelProp = global::Mono.Unix.Catalog.GetString("Your balance:");
			this.hbox8.Add(this.labelBalance);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.labelBalance]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(10));
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelBalanceValue = new global::Gtk.Label();
			this.labelBalanceValue.Name = "labelBalanceValue";
			this.hbox8.Add(this.labelBalanceValue);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.labelBalanceValue]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox4.Add(this.hbox8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.eventboxAmount.Add(this.vbox4);
			this.vboxMainInner.Add(this.eventboxAmount);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.eventboxAmount]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			w32.Padding = ((uint)(5));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonSignAndReview = new global::Gtk.Button();
			this.buttonSignAndReview.WidthRequest = 140;
			this.buttonSignAndReview.HeightRequest = 50;
			this.buttonSignAndReview.CanFocus = true;
			this.buttonSignAndReview.Name = "buttonSignAndReview";
			this.buttonSignAndReview.UseUnderline = true;
			this.buttonSignAndReview.Label = global::Mono.Unix.Catalog.GetString("Sign & Review");
			this.hbox4.Add(this.buttonSignAndReview);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonSignAndReview]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.vboxMainInner.Add(this.hbox4);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hbox4]));
			w34.PackType = ((global::Gtk.PackType)(1));
			w34.Position = 3;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox3.Add(this.vboxMainInner);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vboxMainInner]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
