
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class Log
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.EventBox eventbox4;

		private global::Gtk.TreeView listHeaders;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.EventBox eventbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView listTransactions;

		private global::Gtk.VScrollbar vscrollbar2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.EventBox eventbox5;

		private global::Gtk.TreeView listSummaryHeader;

		private global::Gtk.EventBox eventbox2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.EventBox eventbox6;

		private global::Gtk.TreeView listSummary;

		private global::Gtk.EventBox eventbox3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Log
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Log";
			// Container child Wallet.Log.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox4 = new global::Gtk.EventBox();
			this.eventbox4.WidthRequest = 10;
			this.eventbox4.Name = "eventbox4";
			this.hbox1.Add(this.eventbox4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox4]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.listHeaders = new global::Gtk.TreeView();
			this.listHeaders.Name = "listHeaders";
			this.listHeaders.HeadersVisible = false;
			this.hbox1.Add(this.listHeaders);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.listHeaders]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.WidthRequest = 30;
			this.eventbox1.Name = "eventbox1";
			this.hbox1.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox1]));
			w3.Position = 2;
			w3.Expand = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventbox7 = new global::Gtk.EventBox();
			this.eventbox7.WidthRequest = 10;
			this.eventbox7.Name = "eventbox7";
			this.hbox2.Add(this.eventbox7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.eventbox7]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.listTransactions = new global::Gtk.TreeView();
			this.listTransactions.Name = "listTransactions";
			this.listTransactions.EnableSearch = false;
			this.listTransactions.HeadersVisible = false;
			this.listTransactions.RulesHint = true;
			this.GtkScrolledWindow.Add(this.listTransactions);
			this.hbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vscrollbar2 = new global::Gtk.VScrollbar(null);
			this.vscrollbar2.WidthRequest = 30;
			this.vscrollbar2.Name = "vscrollbar2";
			this.vscrollbar2.Adjustment.Upper = 100;
			this.vscrollbar2.Adjustment.PageIncrement = 10;
			this.vscrollbar2.Adjustment.PageSize = 10;
			this.vscrollbar2.Adjustment.StepIncrement = 1;
			this.hbox2.Add(this.vscrollbar2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vscrollbar2]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w9.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventbox5 = new global::Gtk.EventBox();
			this.eventbox5.WidthRequest = 10;
			this.eventbox5.Name = "eventbox5";
			this.hbox4.Add(this.eventbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventbox5]));
			w10.Position = 0;
			w10.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.listSummaryHeader = new global::Gtk.TreeView();
			this.listSummaryHeader.Name = "listSummaryHeader";
			this.listSummaryHeader.HeadersVisible = false;
			this.hbox4.Add(this.listSummaryHeader);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.listSummaryHeader]));
			w11.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.WidthRequest = 30;
			this.eventbox2.Name = "eventbox2";
			this.hbox4.Add(this.eventbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventbox2]));
			w12.Position = 2;
			w12.Expand = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w13.Position = 2;
			w13.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			// Container child hbox5.Gtk.Box+BoxChild
			this.eventbox6 = new global::Gtk.EventBox();
			this.eventbox6.WidthRequest = 10;
			this.eventbox6.Name = "eventbox6";
			this.hbox5.Add(this.eventbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eventbox6]));
			w14.Position = 0;
			w14.Expand = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.listSummary = new global::Gtk.TreeView();
			this.listSummary.Name = "listSummary";
			this.listSummary.HeadersVisible = false;
			this.hbox5.Add(this.listSummary);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.listSummary]));
			w15.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.eventbox3 = new global::Gtk.EventBox();
			this.eventbox3.WidthRequest = 30;
			this.eventbox3.Name = "eventbox3";
			this.hbox5.Add(this.eventbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eventbox3]));
			w16.Position = 2;
			w16.Expand = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 3;
			w17.Expand = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
