
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet.Widgets.Portfolio
{
	public partial class PortfolioTable
	{
		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.EventBox eventbox4;

		private global::Gtk.TreeView listHeaders;

		private global::Gtk.HBox hbox2;

		private global::Gtk.EventBox eventbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView listPortfolio;

		private global::Gtk.Label label13;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Widgets.Portfolio.PortfolioTable
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Widgets.Portfolio.PortfolioTable";
			// Container child Wallet.Widgets.Portfolio.PortfolioTable.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox4 = new global::Gtk.EventBox();
			this.eventbox4.WidthRequest = 10;
			this.eventbox4.Name = "eventbox4";
			this.hbox1.Add(this.eventbox4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox4]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.listHeaders = new global::Gtk.TreeView();
			this.listHeaders.Name = "listHeaders";
			this.listHeaders.HeadersVisible = false;
			this.hbox1.Add(this.listHeaders);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.listHeaders]));
			w2.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventbox7 = new global::Gtk.EventBox();
			this.eventbox7.WidthRequest = 10;
			this.eventbox7.Name = "eventbox7";
			this.hbox2.Add(this.eventbox7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.eventbox7]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.listPortfolio = new global::Gtk.TreeView();
			this.listPortfolio.Name = "listPortfolio";
			this.listPortfolio.EnableSearch = false;
			this.listPortfolio.HeadersVisible = false;
			this.listPortfolio.RulesHint = true;
			this.GtkScrolledWindow.Add(this.listPortfolio);
			this.hbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w6.Position = 1;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w7.Position = 1;
			this.hbox4.Add(this.vbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox1]));
			w8.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.WidthRequest = 20;
			this.label13.Name = "label13";
			this.hbox4.Add(this.label13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label13]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.hbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
