
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class ImageButton
	{
		private global::Gtk.EventBox eventbox1;
		
		private global::Gtk.Label label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.ImageButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Wallet.ImageButton";
			// Container child Wallet.ImageButton.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label");
			this.eventbox1.Add (this.label);
			this.Add (this.eventbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
