
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Image imageLogo;
		
		private global::Wallet.MainMenu MainMenu1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Wallet.VerticalMenu VerticalMenu1;
		
		private global::Wallet.MainArea mainarea1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.MainWindow
			this.Name = "Wallet.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ZEN Wallet");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			// Container child Wallet.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.imageLogo = new global::Gtk.Image ();
			this.imageLogo.Name = "imageLogo";
			this.imageLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Wallet.Assets.logosmall.png");
			this.hbox4.Add (this.imageLogo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.imageLogo]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(15));
			// Container child vbox1.Gtk.Box+BoxChild
			this.MainMenu1 = new global::Wallet.MainMenu ();
			this.MainMenu1.Events = ((global::Gdk.EventMask)(256));
			this.MainMenu1.Name = "MainMenu1";
			this.vbox1.Add (this.MainMenu1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MainMenu1]));
			w3.Position = 1;
			w3.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.VerticalMenu1 = new global::Wallet.VerticalMenu ();
			this.VerticalMenu1.Events = ((global::Gdk.EventMask)(256));
			this.VerticalMenu1.Name = "VerticalMenu1";
			this.hbox1.Add (this.VerticalMenu1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.VerticalMenu1]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.mainarea1 = new global::Wallet.MainArea ();
			this.mainarea1.Events = ((global::Gdk.EventMask)(256));
			this.mainarea1.Name = "mainarea1";
			this.hbox1.Add (this.mainarea1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.mainarea1]));
			w5.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 936;
			this.DefaultHeight = 936;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
