
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class LogLayout
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label labelHeader;

		private global::Gtk.ComboBox comboboxAsset;

		private global::Wallet.Log log1;

		private global::Wallet.Widgets.Log.LogTotals logtotals1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.LogLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.LogLayout";
			// Container child Wallet.LogLayout.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.BorderWidth = ((uint)(40));
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelHeader = new global::Gtk.Label();
			this.labelHeader.Name = "labelHeader";
			this.labelHeader.Xalign = 0F;
			this.labelHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Your Transactions");
			this.hbox3.Add(this.labelHeader);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelHeader]));
			w1.Position = 0;
			w1.Padding = ((uint)(10));
			// Container child hbox3.Gtk.Box+BoxChild
			this.comboboxAsset = global::Gtk.ComboBox.NewText();
			this.comboboxAsset.Name = "comboboxAsset";
			this.hbox3.Add(this.comboboxAsset);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.comboboxAsset]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.log1 = new global::Wallet.Log();
			this.log1.Events = ((global::Gdk.EventMask)(256));
			this.log1.Name = "log1";
			this.vbox1.Add(this.log1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.log1]));
			w4.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.logtotals1 = new global::Wallet.Widgets.Log.LogTotals();
			this.logtotals1.Events = ((global::Gdk.EventMask)(256));
			this.logtotals1.Name = "logtotals1";
			this.vbox1.Add(this.logtotals1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.logtotals1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
