
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class PortfolioItem
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.PortfolioItem
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.PortfolioItem";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
