
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class WalletSendLayout
	{
		private global::Gtk.VBox vboxMainInner;

		private global::Gtk.HBox hbox6;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label labelHeader;

		private global::Gtk.VBox vboxDestination;

		private global::Gtk.HBox hboxDestinationHeader;

		private global::Gtk.Label labelDestination;

		private global::Gtk.Label labelDestinationError;

		private global::Gtk.HBox hboxDestination;

		private global::Gtk.Entry entryDestination;

		private global::Gtk.EventBox eventboxPasteAddress;

		private global::Gtk.Image image2;

		private global::Gtk.EventBox eventboxSeperator;

		private global::Gtk.VBox vboxData;

		private global::Gtk.HBox hboxDataHeader;

		private global::Gtk.Label labelData;

		private global::Gtk.Label labelDataError;

		private global::Gtk.HBox hboxData;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtData;

		private global::Gtk.VBox vbox4;

		private global::Gtk.EventBox eventboxPasterData;

		private global::Gtk.VBox vboxDataPaste;

		private global::Gtk.Image image5;

		private global::Gtk.EventBox eventboxSeperator1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox vbox;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label labelSelectAsset;

		private global::Gtk.ComboBox comboboxAsset;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hboxAmount;

		private global::Gtk.Label labelAmount;

		private global::Gtk.Label labelAmountError;

		private global::Gtk.Entry entryAmount;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label labelBalanceHeader;

		private global::Gtk.Label labelBalance;

		private global::Gtk.HBox hboxButtons;

		private global::Gtk.EventBox eventboxBack;

		private global::Gtk.Image image1;

		private global::Gtk.Label labelStatus;

		private global::Gtk.HBox hboxSignAndReview;

		private global::Gtk.EventBox eventboxSend;

		private global::Gtk.Image imageSignAndReview;

		private global::Gtk.Image imageSignAndReviewDisabled;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.WalletSendLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.WalletSendLayout";
			// Container child Wallet.WalletSendLayout.Gtk.Container+ContainerChild
			this.vboxMainInner = new global::Gtk.VBox();
			this.vboxMainInner.Name = "vboxMainInner";
			this.vboxMainInner.BorderWidth = ((uint)(20));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			this.hbox6.BorderWidth = ((uint)(20));
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelHeader = new global::Gtk.Label();
			this.labelHeader.Name = "labelHeader";
			this.labelHeader.Xalign = 0F;
			this.labelHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Send");
			this.hbox5.Add(this.labelHeader);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.labelHeader]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.hbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(10));
			this.vboxMainInner.Add(this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.vboxDestination = new global::Gtk.VBox();
			this.vboxDestination.Name = "vboxDestination";
			this.vboxDestination.BorderWidth = ((uint)(10));
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.hboxDestinationHeader = new global::Gtk.HBox();
			this.hboxDestinationHeader.Name = "hboxDestinationHeader";
			this.hboxDestinationHeader.Spacing = -3;
			// Container child hboxDestinationHeader.Gtk.Box+BoxChild
			this.labelDestination = new global::Gtk.Label();
			this.labelDestination.Name = "labelDestination";
			this.labelDestination.LabelProp = global::Mono.Unix.Catalog.GetString("Destination:");
			this.hboxDestinationHeader.Add(this.labelDestination);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxDestinationHeader[this.labelDestination]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(20));
			// Container child hboxDestinationHeader.Gtk.Box+BoxChild
			this.labelDestinationError = new global::Gtk.Label();
			this.labelDestinationError.Name = "labelDestinationError";
			this.labelDestinationError.LabelProp = global::Mono.Unix.Catalog.GetString("Invalid");
			this.hboxDestinationHeader.Add(this.labelDestinationError);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxDestinationHeader[this.labelDestinationError]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vboxDestination.Add(this.hboxDestinationHeader);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.hboxDestinationHeader]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.hboxDestination = new global::Gtk.HBox();
			this.hboxDestination.Name = "hboxDestination";
			this.hboxDestination.BorderWidth = ((uint)(10));
			// Container child hboxDestination.Gtk.Box+BoxChild
			this.entryDestination = new global::Gtk.Entry();
			this.entryDestination.HeightRequest = 35;
			this.entryDestination.CanFocus = true;
			this.entryDestination.Name = "entryDestination";
			this.entryDestination.IsEditable = true;
			this.entryDestination.InvisibleChar = '●';
			this.hboxDestination.Add(this.entryDestination);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxDestination[this.entryDestination]));
			w7.Position = 0;
			w7.Padding = ((uint)(5));
			// Container child hboxDestination.Gtk.Box+BoxChild
			this.eventboxPasteAddress = new global::Gtk.EventBox();
			this.eventboxPasteAddress.Name = "eventboxPasteAddress";
			// Container child eventboxPasteAddress.Gtk.Container+ContainerChild
			this.image2 = new global::Gtk.Image();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Paste.png");
			this.eventboxPasteAddress.Add(this.image2);
			this.hboxDestination.Add(this.eventboxPasteAddress);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxDestination[this.eventboxPasteAddress]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			w9.Padding = ((uint)(5));
			this.vboxDestination.Add(this.hboxDestination);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.hboxDestination]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.eventboxSeperator = new global::Gtk.EventBox();
			this.eventboxSeperator.HeightRequest = 1;
			this.eventboxSeperator.Name = "eventboxSeperator";
			this.vboxDestination.Add(this.eventboxSeperator);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.eventboxSeperator]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 2;
			w11.Padding = ((uint)(4));
			this.vboxMainInner.Add(this.vboxDestination);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.vboxDestination]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Padding = ((uint)(5));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.vboxData = new global::Gtk.VBox();
			this.vboxData.HeightRequest = 125;
			this.vboxData.Name = "vboxData";
			this.vboxData.BorderWidth = ((uint)(10));
			// Container child vboxData.Gtk.Box+BoxChild
			this.hboxDataHeader = new global::Gtk.HBox();
			this.hboxDataHeader.Name = "hboxDataHeader";
			this.hboxDataHeader.Spacing = -3;
			// Container child hboxDataHeader.Gtk.Box+BoxChild
			this.labelData = new global::Gtk.Label();
			this.labelData.Name = "labelData";
			this.labelData.LabelProp = global::Mono.Unix.Catalog.GetString("Data:");
			this.hboxDataHeader.Add(this.labelData);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxDataHeader[this.labelData]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(20));
			// Container child hboxDataHeader.Gtk.Box+BoxChild
			this.labelDataError = new global::Gtk.Label();
			this.labelDataError.Name = "labelDataError";
			this.labelDataError.LabelProp = global::Mono.Unix.Catalog.GetString("Invalid");
			this.hboxDataHeader.Add(this.labelDataError);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxDataHeader[this.labelDataError]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vboxData.Add(this.hboxDataHeader);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxData[this.hboxDataHeader]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vboxData.Gtk.Box+BoxChild
			this.hboxData = new global::Gtk.HBox();
			this.hboxData.Name = "hboxData";
			this.hboxData.BorderWidth = ((uint)(10));
			// Container child hboxData.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtData = new global::Gtk.TextView();
			this.txtData.CanFocus = true;
			this.txtData.Name = "txtData";
			this.txtData.WrapMode = ((global::Gtk.WrapMode)(3));
			this.txtData.Indent = 4;
			this.GtkScrolledWindow.Add(this.txtData);
			this.hboxData.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxData[this.GtkScrolledWindow]));
			w17.Position = 0;
			w17.Padding = ((uint)(7));
			// Container child hboxData.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.eventboxPasterData = new global::Gtk.EventBox();
			this.eventboxPasterData.Name = "eventboxPasterData";
			// Container child eventboxPasterData.Gtk.Container+ContainerChild
			this.vboxDataPaste = new global::Gtk.VBox();
			this.vboxDataPaste.Name = "vboxDataPaste";
			this.vboxDataPaste.Spacing = 6;
			// Container child vboxDataPaste.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image();
			this.image5.Name = "image5";
			this.image5.Yalign = 0F;
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Paste.png");
			this.vboxDataPaste.Add(this.image5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxDataPaste[this.image5]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			this.eventboxPasterData.Add(this.vboxDataPaste);
			this.vbox4.Add(this.eventboxPasterData);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.eventboxPasterData]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			this.hboxData.Add(this.vbox4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hboxData[this.vbox4]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(5));
			this.vboxData.Add(this.hboxData);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vboxData[this.hboxData]));
			w22.Position = 1;
			// Container child vboxData.Gtk.Box+BoxChild
			this.eventboxSeperator1 = new global::Gtk.EventBox();
			this.eventboxSeperator1.HeightRequest = 1;
			this.eventboxSeperator1.Name = "eventboxSeperator1";
			this.vboxData.Add(this.eventboxSeperator1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxData[this.eventboxSeperator1]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(4));
			this.vboxMainInner.Add(this.vboxData);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.vboxData]));
			w24.Position = 2;
			w24.Expand = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 15;
			this.label1.Name = "label1";
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.HBox();
			this.vbox.Name = "vbox";
			this.vbox.Homogeneous = true;
			this.vbox.Spacing = 30;
			this.vbox.BorderWidth = ((uint)(10));
			// Container child vbox.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelSelectAsset = new global::Gtk.Label();
			this.labelSelectAsset.Name = "labelSelectAsset";
			this.labelSelectAsset.Xalign = 0F;
			this.labelSelectAsset.LabelProp = global::Mono.Unix.Catalog.GetString("Select asset:");
			this.vbox1.Add(this.labelSelectAsset);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelSelectAsset]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.comboboxAsset = global::Gtk.ComboBox.NewText();
			this.comboboxAsset.HeightRequest = 35;
			this.comboboxAsset.Name = "comboboxAsset";
			this.vbox1.Add(this.comboboxAsset);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.comboboxAsset]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox.Add(this.vbox1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox[this.vbox1]));
			w28.Position = 0;
			// Container child vbox.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hboxAmount = new global::Gtk.HBox();
			this.hboxAmount.Name = "hboxAmount";
			this.hboxAmount.Spacing = 6;
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.labelAmount = new global::Gtk.Label();
			this.labelAmount.Name = "labelAmount";
			this.labelAmount.Xalign = 0F;
			this.labelAmount.LabelProp = global::Mono.Unix.Catalog.GetString("Amount to send:");
			this.hboxAmount.Add(this.labelAmount);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hboxAmount[this.labelAmount]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.labelAmountError = new global::Gtk.Label();
			this.labelAmountError.Name = "labelAmountError";
			this.labelAmountError.LabelProp = global::Mono.Unix.Catalog.GetString("Invalid");
			this.hboxAmount.Add(this.labelAmountError);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hboxAmount[this.labelAmountError]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox5.Add(this.hboxAmount);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hboxAmount]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.entryAmount = new global::Gtk.Entry();
			this.entryAmount.HeightRequest = 35;
			this.entryAmount.CanFocus = true;
			this.entryAmount.Name = "entryAmount";
			this.entryAmount.IsEditable = true;
			this.entryAmount.InvisibleChar = '●';
			this.vbox5.Add(this.entryAmount);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.entryAmount]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox.Add(this.vbox5);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox[this.vbox5]));
			w33.Position = 1;
			// Container child vbox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.labelBalanceHeader = new global::Gtk.Label();
			this.labelBalanceHeader.Name = "labelBalanceHeader";
			this.labelBalanceHeader.Xalign = 0F;
			this.labelBalanceHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Your balance:");
			this.vbox6.Add(this.labelBalanceHeader);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.labelBalanceHeader]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.labelBalance = new global::Gtk.Label();
			this.labelBalance.HeightRequest = 40;
			this.labelBalance.Name = "labelBalance";
			this.labelBalance.Xalign = 0F;
			this.vbox6.Add(this.labelBalance);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.labelBalance]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox.Add(this.vbox6);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox[this.vbox6]));
			w36.Position = 2;
			this.hbox1.Add(this.vbox);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox]));
			w37.Position = 1;
			this.vboxMainInner.Add(this.hbox1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hbox1]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.BorderWidth = ((uint)(25));
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.eventboxBack = new global::Gtk.EventBox();
			this.eventboxBack.Name = "eventboxBack";
			// Container child eventboxBack.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Back.png");
			this.eventboxBack.Add(this.image1);
			this.hboxButtons.Add(this.eventboxBack);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.eventboxBack]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.Xpad = 10;
			this.labelStatus.Xalign = 1F;
			this.hboxButtons.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.labelStatus]));
			w41.Position = 1;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.hboxSignAndReview = new global::Gtk.HBox();
			this.hboxSignAndReview.Name = "hboxSignAndReview";
			// Container child hboxSignAndReview.Gtk.Box+BoxChild
			this.eventboxSend = new global::Gtk.EventBox();
			this.eventboxSend.Name = "eventboxSend";
			// Container child eventboxSend.Gtk.Container+ContainerChild
			this.imageSignAndReview = new global::Gtk.Image();
			this.imageSignAndReview.Name = "imageSignAndReview";
			this.imageSignAndReview.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Sign_and_Review.png");
			this.eventboxSend.Add(this.imageSignAndReview);
			this.hboxSignAndReview.Add(this.eventboxSend);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hboxSignAndReview[this.eventboxSend]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hboxSignAndReview.Gtk.Box+BoxChild
			this.imageSignAndReviewDisabled = new global::Gtk.Image();
			this.imageSignAndReviewDisabled.Name = "imageSignAndReviewDisabled";
			this.imageSignAndReviewDisabled.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Sign_and_Review_disabled.png");
			this.hboxSignAndReview.Add(this.imageSignAndReviewDisabled);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hboxSignAndReview[this.imageSignAndReviewDisabled]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			this.hboxButtons.Add(this.hboxSignAndReview);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.hboxSignAndReview]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.vboxMainInner.Add(this.hboxButtons);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hboxButtons]));
			w46.PackType = ((global::Gtk.PackType)(1));
			w46.Position = 4;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.vboxMainInner.Add(this.label5);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.label5]));
			w47.PackType = ((global::Gtk.PackType)(1));
			w47.Position = 5;
			this.Add(this.vboxMainInner);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
