
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class MainArea
	{
		private global::Gtk.Notebook notebook1;

		private global::Wallet.WalletLayout walletlayout1;

		private global::Gtk.Label label3;

		private global::Wallet.Portfolio portfolio1;

		private global::Gtk.Label label12;

		private global::Wallet.Contract contract1;

		private global::Gtk.Label label13;

		private global::Wallet.LogLayout loglayout1;

		private global::Gtk.Label label15;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.MainArea
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.MainArea";
			// Container child Wallet.MainArea.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.ShowBorder = false;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletlayout1 = new global::Wallet.WalletLayout();
			this.walletlayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletlayout1.Name = "walletlayout1";
			this.notebook1.Add(this.walletlayout1);
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("page5");
			this.notebook1.SetTabLabel(this.walletlayout1, this.label3);
			this.label3.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.portfolio1 = new global::Wallet.Portfolio();
			this.portfolio1.Events = ((global::Gdk.EventMask)(256));
			this.portfolio1.Name = "portfolio1";
			this.notebook1.Add(this.portfolio1);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.portfolio1]));
			w2.Position = 1;
			// Notebook tab
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("page4");
			this.notebook1.SetTabLabel(this.portfolio1, this.label12);
			this.label12.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.contract1 = new global::Wallet.Contract();
			this.contract1.Events = ((global::Gdk.EventMask)(256));
			this.contract1.Name = "contract1";
			this.notebook1.Add(this.contract1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.contract1]));
			w3.Position = 2;
			// Notebook tab
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("page2");
			this.notebook1.SetTabLabel(this.contract1, this.label13);
			this.label13.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.loglayout1 = new global::Wallet.LogLayout();
			this.loglayout1.Events = ((global::Gdk.EventMask)(256));
			this.loglayout1.Name = "loglayout1";
			this.notebook1.Add(this.loglayout1);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.loglayout1]));
			w4.Position = 3;
			// Notebook tab
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
			this.notebook1.SetTabLabel(this.loglayout1, this.label15);
			this.label15.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
