
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class MainArea
	{
		private global::Gtk.Notebook notebook1;
		
		private global::Wallet.Wallet wallet1;
		
		private global::Gtk.Label label2;
		
		private global::Wallet.Contract contract1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.MainArea
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Wallet.MainArea";
			// Container child Wallet.MainArea.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.ShowBorder = false;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.wallet1 = new global::Wallet.Wallet ();
			this.wallet1.Events = ((global::Gdk.EventMask)(256));
			this.wallet1.Name = "wallet1";
			this.notebook1.Add (this.wallet1);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.notebook1.SetTabLabel (this.wallet1, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.contract1 = new global::Wallet.Contract ();
			this.contract1.Events = ((global::Gdk.EventMask)(256));
			this.contract1.Name = "contract1";
			this.notebook1.Add (this.contract1);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.contract1]));
			w2.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.notebook1.SetTabLabel (this.contract1, this.label3);
			this.label3.ShowAll ();
			// Notebook tab
			global::Gtk.Label w3 = new global::Gtk.Label ();
			w3.Visible = true;
			this.notebook1.Add (w3);
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
			this.notebook1.SetTabLabel (w3, this.label6);
			this.label6.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
