
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class SendDialog
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Image image;
		
		private global::Gtk.HBox hboxTo;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.HBox hboxAmount;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry entry4;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.HBox hboxSendButton;
		
		private global::Gtk.EventBox eventboxSend;
		
		private global::Gtk.Image imageSend;
		
		private global::Gtk.HBox hboxFooter;
		
		private global::Gtk.Label labelBalance;
		
		private global::Gtk.Label labelFee;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.SendDialog
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 650;
			this.Name = "Wallet.SendDialog";
			// Container child Wallet.SendDialog.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(15));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("SEND");
			this.vbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.vbox1.Add (this.image);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxTo = new global::Gtk.HBox ();
			this.hboxTo.Name = "hboxTo";
			this.hboxTo.Spacing = 6;
			// Container child hboxTo.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.WidthRequest = 100;
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("TO");
			this.hboxTo.Add (this.label7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxTo [this.label7]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxTo.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hboxTo.Add (this.entry3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxTo [this.entry3]));
			w4.Position = 1;
			// Container child hboxTo.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.WidthRequest = 100;
			this.label8.Name = "label8";
			this.label8.Justify = ((global::Gtk.Justification)(1));
			this.hboxTo.Add (this.label8);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxTo [this.label8]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hboxTo);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxTo]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxAmount = new global::Gtk.HBox ();
			this.hboxAmount.Name = "hboxAmount";
			this.hboxAmount.Spacing = 6;
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.WidthRequest = 100;
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("AMOUNT");
			this.label9.Justify = ((global::Gtk.Justification)(1));
			this.hboxAmount.Add (this.label9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxAmount [this.label9]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.hboxAmount.Add (this.entry4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxAmount [this.entry4]));
			w8.Position = 1;
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.WidthRequest = 100;
			this.label10.Name = "label10";
			this.label10.Justify = ((global::Gtk.Justification)(1));
			this.hboxAmount.Add (this.label10);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxAmount [this.label10]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add (this.hboxAmount);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxAmount]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxSendButton = new global::Gtk.HBox ();
			this.hboxSendButton.Name = "hboxSendButton";
			this.hboxSendButton.Homogeneous = true;
			this.hboxSendButton.Spacing = 6;
			// Container child hboxSendButton.Gtk.Box+BoxChild
			this.eventboxSend = new global::Gtk.EventBox ();
			this.eventboxSend.Name = "eventboxSend";
			// Container child eventboxSend.Gtk.Container+ContainerChild
			this.imageSend = new global::Gtk.Image ();
			this.imageSend.Name = "imageSend";
			this.eventboxSend.Add (this.imageSend);
			this.hboxSendButton.Add (this.eventboxSend);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxSendButton [this.eventboxSend]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hboxSendButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxSendButton]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxFooter = new global::Gtk.HBox ();
			this.hboxFooter.Name = "hboxFooter";
			this.hboxFooter.Homogeneous = true;
			this.hboxFooter.Spacing = 6;
			// Container child hboxFooter.Gtk.Box+BoxChild
			this.labelBalance = new global::Gtk.Label ();
			this.labelBalance.Name = "labelBalance";
			this.labelBalance.Xalign = 0F;
			this.labelBalance.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.hboxFooter.Add (this.labelBalance);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxFooter [this.labelBalance]));
			w14.Position = 0;
			// Container child hboxFooter.Gtk.Box+BoxChild
			this.labelFee = new global::Gtk.Label ();
			this.labelFee.Name = "labelFee";
			this.labelFee.Xalign = 1F;
			this.labelFee.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.hboxFooter.Add (this.labelFee);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxFooter [this.labelFee]));
			w15.Position = 1;
			this.vbox1.Add (this.hboxFooter);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hboxFooter]));
			w16.Position = 5;
			w16.Expand = false;
			w16.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
