
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet.Widgets.Portfolio
{
	public partial class PortfolioTotals
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.EventBox eventbox2;

		private global::Gtk.EventBox eventbox3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelBalance;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Widgets.Portfolio.PortfolioTotals
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Widgets.Portfolio.PortfolioTotals";
			// Container child Wallet.Widgets.Portfolio.PortfolioTotals.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Homogeneous = true;
			this.hbox1.BorderWidth = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			this.hbox1.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox1]));
			w1.Position = 0;
			w1.Padding = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.Name = "eventbox2";
			this.hbox1.Add(this.eventbox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox2]));
			w2.Position = 1;
			w2.Padding = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox3 = new global::Gtk.EventBox();
			this.eventbox3.Name = "eventbox3";
			// Container child eventbox3.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xpad = 8;
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("TOTAL ZEN BALANCE:");
			this.vbox3.Add(this.label9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label9]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelBalance = new global::Gtk.Label();
			this.labelBalance.Name = "labelBalance";
			this.labelBalance.Xpad = 8;
			this.labelBalance.Xalign = 0F;
			this.labelBalance.LabelProp = global::Mono.Unix.Catalog.GetString("Balance");
			this.vbox3.Add(this.labelBalance);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.labelBalance]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.eventbox3.Add(this.vbox3);
			this.hbox1.Add(this.eventbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox3]));
			w6.Position = 2;
			w6.Padding = ((uint)(5));
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
