
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet.Widgets.Portfolio
{
	public partial class PortfolioLayout
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label labelHeader;

		private global::Wallet.Widgets.Portfolio.PortfolioTable portfoliotable1;

		private global::Wallet.Widgets.Portfolio.PortfolioTotals portfoliototals;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Widgets.Portfolio.PortfolioLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Widgets.Portfolio.PortfolioLayout";
			// Container child Wallet.Widgets.Portfolio.PortfolioLayout.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.BorderWidth = ((uint)(40));
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelHeader = new global::Gtk.Label();
			this.labelHeader.Name = "labelHeader";
			this.labelHeader.Xalign = 0F;
			this.labelHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Your Portfolio");
			this.hbox3.Add(this.labelHeader);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelHeader]));
			w1.Position = 0;
			w1.Padding = ((uint)(10));
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.portfoliotable1 = new global::Wallet.Widgets.Portfolio.PortfolioTable();
			this.portfoliotable1.Events = ((global::Gdk.EventMask)(256));
			this.portfoliotable1.Name = "portfoliotable1";
			this.vbox1.Add(this.portfoliotable1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.portfoliotable1]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.portfoliototals = new global::Wallet.Widgets.Portfolio.PortfolioTotals();
			this.portfoliototals.Events = ((global::Gdk.EventMask)(256));
			this.portfoliototals.Name = "portfoliototals";
			this.vbox1.Add(this.portfoliototals);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.portfoliototals]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
