
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class ContractActivation
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label4;

		private global::Gtk.Label labelHeader;

		private global::Gtk.EventBox eventboxClose;

		private global::Gtk.Image image5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtContent;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.Label label1;

		private global::Gtk.SpinButton spinBlocks;

		private global::Gtk.Label labelKalapas;

		private global::Gtk.Label label5;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button buttonApply;

		private global::Gtk.HBox hboxStatus;

		private global::Gtk.Label labelStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.ContractActivation
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 400;
			this.Name = "Wallet.ContractActivation";
			// Container child Wallet.ContractActivation.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 50;
			this.label4.Name = "label4";
			this.hbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelHeader = new global::Gtk.Label();
			this.labelHeader.Name = "labelHeader";
			this.labelHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Header");
			this.hbox3.Add(this.labelHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelHeader]));
			w2.Position = 1;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventboxClose = new global::Gtk.EventBox();
			this.eventboxClose.Name = "eventboxClose";
			// Container child eventboxClose.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image();
			this.image5.WidthRequest = 50;
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			this.eventboxClose.Add(this.image5);
			this.hbox3.Add(this.eventboxClose);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.eventboxClose]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtContent = new global::Gtk.TextView();
			this.txtContent.CanFocus = true;
			this.txtContent.Name = "txtContent";
			this.txtContent.Editable = false;
			this.GtkScrolledWindow.Add(this.txtContent);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.hbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Blocks:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.spinBlocks = new global::Gtk.SpinButton(0, 100, 1);
			this.spinBlocks.CanFocus = true;
			this.spinBlocks.Name = "spinBlocks";
			this.spinBlocks.Adjustment.PageIncrement = 10;
			this.spinBlocks.ClimbRate = 1;
			this.spinBlocks.Numeric = true;
			this.spinBlocks.Value = 1;
			this.hbox1.Add(this.spinBlocks);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.spinBlocks]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelKalapas = new global::Gtk.Label();
			this.labelKalapas.Name = "labelKalapas";
			this.hbox1.Add(this.labelKalapas);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelKalapas]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.hbox1.Add(this.label5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label5]));
			w12.Position = 4;
			w12.Fill = false;
			this.vbox3.Add(this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonApply = new global::Gtk.Button();
			this.buttonApply.CanFocus = true;
			this.buttonApply.Name = "buttonApply";
			this.buttonApply.UseUnderline = true;
			this.buttonApply.Label = global::Mono.Unix.Catalog.GetString("Button");
			this.hbox2.Add(this.buttonApply);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonApply]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hboxStatus = new global::Gtk.HBox();
			this.hboxStatus.Name = "hboxStatus";
			this.hboxStatus.Homogeneous = true;
			this.hboxStatus.Spacing = 6;
			// Container child hboxStatus.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.hboxStatus.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hboxStatus[this.labelStatus]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox3.Add(this.hboxStatus);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hboxStatus]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.hboxStatus.Hide();
			this.Hide();
		}
	}
}
