
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class Contract
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView txtContractCode;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.EventBox eventboxLoad;

		private global::Gtk.Image image4;

		private global::Gtk.Button buttonSave;

		private global::Gtk.Entry txtContractHash;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtStatus;

		private global::Gtk.HBox hbox4;

		private global::Gtk.EventBox eventboxValidate;

		private global::Gtk.Image image;

		private global::Gtk.EventBox eventboxCreateOrExtend;

		private global::Gtk.Image image6;

		private global::Gtk.Label labelStatus;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TextView textview3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Contract
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Contract";
			// Container child Wallet.Contract.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtContractCode = new global::Gtk.TextView();
			this.txtContractCode.CanFocus = true;
			this.txtContractCode.Name = "txtContractCode";
			this.GtkScrolledWindow1.Add(this.txtContractCode);
			this.hbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.WidthRequest = 500;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventboxLoad = new global::Gtk.EventBox();
			this.eventboxLoad.Name = "eventboxLoad";
			this.eventboxLoad.VisibleWindow = false;
			// Container child eventboxLoad.Gtk.Container+ContainerChild
			this.image4 = new global::Gtk.Image();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.Contract.Load.png");
			this.eventboxLoad.Add(this.image4);
			this.hbox3.Add(this.eventboxLoad);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.eventboxLoad]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Save");
			this.hbox3.Add(this.buttonSave);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonSave]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtContractHash = new global::Gtk.Entry();
			this.txtContractHash.CanFocus = true;
			this.txtContractHash.Name = "txtContractHash";
			this.txtContractHash.IsEditable = true;
			this.txtContractHash.InvisibleChar = '●';
			this.hbox3.Add(this.txtContractHash);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtContractHash]));
			w6.Position = 2;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtStatus = new global::Gtk.TextView();
			this.txtStatus.CanFocus = true;
			this.txtStatus.Name = "txtStatus";
			this.txtStatus.Editable = false;
			this.GtkScrolledWindow.Add(this.txtStatus);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w9.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventboxValidate = new global::Gtk.EventBox();
			this.eventboxValidate.Name = "eventboxValidate";
			this.eventboxValidate.VisibleWindow = false;
			// Container child eventboxValidate.Gtk.Container+ContainerChild
			this.image = new global::Gtk.Image();
			this.image.Name = "image";
			this.image.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.Contract.Verify.png");
			this.eventboxValidate.Add(this.image);
			this.hbox4.Add(this.eventboxValidate);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventboxValidate]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventboxCreateOrExtend = new global::Gtk.EventBox();
			this.eventboxCreateOrExtend.Name = "eventboxCreateOrExtend";
			this.eventboxCreateOrExtend.VisibleWindow = false;
			// Container child eventboxCreateOrExtend.Gtk.Container+ContainerChild
			this.image6 = new global::Gtk.Image();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.Contract.Create.png");
			this.eventboxCreateOrExtend.Add(this.image6);
			this.hbox4.Add(this.eventboxCreateOrExtend);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventboxCreateOrExtend]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.hbox4.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.labelStatus]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow2.Add(this.textview3);
			this.vbox1.Add(this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow2]));
			w17.Position = 3;
			this.hbox2.Add(this.vbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox1]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
