
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class AddKeyDialog
	{
		private global::Gtk.VBox vbox1;

		private global::Wallet.DialogField dialogfield1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button buttonCreate;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.AddKeyDialog
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.AddKeyDialog";
			// Container child Wallet.AddKeyDialog.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.dialogfield1 = new global::Wallet.DialogField();
			this.dialogfield1.Events = ((global::Gdk.EventMask)(256));
			this.dialogfield1.Name = "dialogfield1";
			this.vbox1.Add(this.dialogfield1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.dialogfield1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCreate = new global::Gtk.Button();
			this.buttonCreate.CanFocus = true;
			this.buttonCreate.Name = "buttonCreate";
			this.buttonCreate.UseUnderline = true;
			this.buttonCreate.Label = global::Mono.Unix.Catalog.GetString("Create");
			this.hbox1.Add(this.buttonCreate);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonCreate]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
