
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class Log
	{
		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.EventBox eventbox4;

		private global::Gtk.TreeView listHeaders;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.EventBox eventbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView listTransactions;

		private global::Gtk.VScrollbar vscrollbar2;

		private global::Gtk.Label label13;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Log
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Log";
			// Container child Wallet.Log.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox4 = new global::Gtk.EventBox();
			this.eventbox4.WidthRequest = 10;
			this.eventbox4.Name = "eventbox4";
			this.hbox1.Add(this.eventbox4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox4]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.listHeaders = new global::Gtk.TreeView();
			this.listHeaders.Name = "listHeaders";
			this.listHeaders.HeadersVisible = false;
			this.hbox1.Add(this.listHeaders);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.listHeaders]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.WidthRequest = 30;
			this.eventbox1.Name = "eventbox1";
			this.hbox1.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.eventbox1]));
			w3.Position = 2;
			w3.Expand = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventbox7 = new global::Gtk.EventBox();
			this.eventbox7.WidthRequest = 10;
			this.eventbox7.Name = "eventbox7";
			this.hbox2.Add(this.eventbox7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.eventbox7]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.listTransactions = new global::Gtk.TreeView();
			this.listTransactions.Name = "listTransactions";
			this.listTransactions.EnableSearch = false;
			this.listTransactions.HeadersVisible = false;
			this.listTransactions.RulesHint = true;
			this.GtkScrolledWindow.Add(this.listTransactions);
			this.hbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vscrollbar2 = new global::Gtk.VScrollbar(null);
			this.vscrollbar2.WidthRequest = 30;
			this.vscrollbar2.Name = "vscrollbar2";
			this.vscrollbar2.Adjustment.Upper = 100;
			this.vscrollbar2.Adjustment.PageIncrement = 10;
			this.vscrollbar2.Adjustment.PageSize = 10;
			this.vscrollbar2.Adjustment.StepIncrement = 1;
			this.hbox2.Add(this.vscrollbar2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vscrollbar2]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w9.Position = 1;
			this.hbox4.Add(this.vbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox1]));
			w10.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.WidthRequest = 20;
			this.label13.Name = "label13";
			this.hbox4.Add(this.label13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label13]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.Add(this.hbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
