
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet.Widgets.Contract
{
	public partial class ContractLayout
	{
		private global::Gtk.VBox vboxMainInner;

		private global::Gtk.HBox hbox6;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label labelHeader;

		private global::Gtk.VBox vboxData;

		private global::Gtk.HBox hboxDataHeader;

		private global::Gtk.Label labelData;

		private global::Gtk.HBox hboxData;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtCode;

		private global::Gtk.VBox vbox4;

		private global::Gtk.EventBox eventboxPasterData;

		private global::Gtk.VBox vboxDataPaste;

		private global::Gtk.Image image5;

		private global::Gtk.EventBox eventboxSeperator1;

		private global::Gtk.VBox vboxDestination;

		private global::Gtk.HBox hboxDestinationHeader;

		private global::Gtk.Label labelDestination;

		private global::Gtk.HBox hboxDestination;

		private global::Gtk.Entry txtHash;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.EventBox eventboxSeperator2;

		private global::Gtk.HBox hboxCostPerBlock;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label8;

		private global::Gtk.Label labelCostPerBlock;

		private global::Gtk.Label label9;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox vbox;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hboxAmount;

		private global::Gtk.Label labelBlocks;

		private global::Gtk.Label labelAmountError;

		private global::Gtk.SpinButton spinbuttonAmount;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hboxAmount1;

		private global::Gtk.Label labelSelectSecureToken;

		private global::Gtk.Label labelSecureTokenError;

		private global::Gtk.ComboBox comboboxAsset;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hboxAmount2;

		private global::Gtk.Label labelCostTotal;

		private global::Gtk.Label labelTotalCost;

		private global::Gtk.HBox hboxButtons;

		private global::Gtk.Label labelStatus;

		private global::Gtk.HBox hboxSignAndReview;

		private global::Gtk.EventBox eventboxActivate;

		private global::Gtk.Image imageActivate;

		private global::Gtk.Image imageActivateDisabled;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Widgets.Contract.ContractLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Widgets.Contract.ContractLayout";
			// Container child Wallet.Widgets.Contract.ContractLayout.Gtk.Container+ContainerChild
			this.vboxMainInner = new global::Gtk.VBox();
			this.vboxMainInner.Name = "vboxMainInner";
			this.vboxMainInner.BorderWidth = ((uint)(20));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			this.hbox6.BorderWidth = ((uint)(20));
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelHeader = new global::Gtk.Label();
			this.labelHeader.Name = "labelHeader";
			this.labelHeader.Xalign = 0F;
			this.labelHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Contract Activation");
			this.hbox5.Add(this.labelHeader);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.labelHeader]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.hbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(10));
			this.vboxMainInner.Add(this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.vboxData = new global::Gtk.VBox();
			this.vboxData.HeightRequest = 125;
			this.vboxData.Name = "vboxData";
			this.vboxData.BorderWidth = ((uint)(10));
			// Container child vboxData.Gtk.Box+BoxChild
			this.hboxDataHeader = new global::Gtk.HBox();
			this.hboxDataHeader.Name = "hboxDataHeader";
			this.hboxDataHeader.Spacing = -3;
			// Container child hboxDataHeader.Gtk.Box+BoxChild
			this.labelData = new global::Gtk.Label();
			this.labelData.Name = "labelData";
			this.labelData.LabelProp = global::Mono.Unix.Catalog.GetString("Code:");
			this.hboxDataHeader.Add(this.labelData);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxDataHeader[this.labelData]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(20));
			this.vboxData.Add(this.hboxDataHeader);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxData[this.hboxDataHeader]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxData.Gtk.Box+BoxChild
			this.hboxData = new global::Gtk.HBox();
			this.hboxData.Name = "hboxData";
			this.hboxData.BorderWidth = ((uint)(10));
			// Container child hboxData.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtCode = new global::Gtk.TextView();
			this.txtCode.CanFocus = true;
			this.txtCode.Name = "txtCode";
			this.txtCode.WrapMode = ((global::Gtk.WrapMode)(3));
			this.txtCode.PixelsAboveLines = 2;
			this.txtCode.PixelsInsideWrap = 2;
			this.txtCode.LeftMargin = 3;
			this.txtCode.RightMargin = 3;
			this.txtCode.Indent = 4;
			this.GtkScrolledWindow.Add(this.txtCode);
			this.hboxData.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxData[this.GtkScrolledWindow]));
			w7.Position = 0;
			w7.Padding = ((uint)(7));
			// Container child hboxData.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.eventboxPasterData = new global::Gtk.EventBox();
			this.eventboxPasterData.Name = "eventboxPasterData";
			// Container child eventboxPasterData.Gtk.Container+ContainerChild
			this.vboxDataPaste = new global::Gtk.VBox();
			this.vboxDataPaste.Name = "vboxDataPaste";
			this.vboxDataPaste.Spacing = 6;
			// Container child vboxDataPaste.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image();
			this.image5.Name = "image5";
			this.image5.Yalign = 0F;
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Paste.png");
			this.vboxDataPaste.Add(this.image5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxDataPaste[this.image5]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.eventboxPasterData.Add(this.vboxDataPaste);
			this.vbox4.Add(this.eventboxPasterData);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.eventboxPasterData]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.hboxData.Add(this.vbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxData[this.vbox4]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(5));
			this.vboxData.Add(this.hboxData);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxData[this.hboxData]));
			w12.Position = 1;
			// Container child vboxData.Gtk.Box+BoxChild
			this.eventboxSeperator1 = new global::Gtk.EventBox();
			this.eventboxSeperator1.HeightRequest = 1;
			this.eventboxSeperator1.Name = "eventboxSeperator1";
			this.vboxData.Add(this.eventboxSeperator1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxData[this.eventboxSeperator1]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(4));
			this.vboxMainInner.Add(this.vboxData);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.vboxData]));
			w14.Position = 1;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.vboxDestination = new global::Gtk.VBox();
			this.vboxDestination.Name = "vboxDestination";
			this.vboxDestination.BorderWidth = ((uint)(10));
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.hboxDestinationHeader = new global::Gtk.HBox();
			this.hboxDestinationHeader.Name = "hboxDestinationHeader";
			this.hboxDestinationHeader.Spacing = -3;
			// Container child hboxDestinationHeader.Gtk.Box+BoxChild
			this.labelDestination = new global::Gtk.Label();
			this.labelDestination.Name = "labelDestination";
			this.labelDestination.LabelProp = global::Mono.Unix.Catalog.GetString("Hash:");
			this.hboxDestinationHeader.Add(this.labelDestination);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxDestinationHeader[this.labelDestination]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(20));
			this.vboxDestination.Add(this.hboxDestinationHeader);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.hboxDestinationHeader]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.hboxDestination = new global::Gtk.HBox();
			this.hboxDestination.Name = "hboxDestination";
			this.hboxDestination.BorderWidth = ((uint)(10));
			// Container child hboxDestination.Gtk.Box+BoxChild
			this.txtHash = new global::Gtk.Entry();
			this.txtHash.HeightRequest = 35;
			this.txtHash.CanFocus = true;
			this.txtHash.Name = "txtHash";
			this.txtHash.IsEditable = false;
			this.txtHash.InvisibleChar = '●';
			this.hboxDestination.Add(this.txtHash);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxDestination[this.txtHash]));
			w17.Position = 0;
			w17.Padding = ((uint)(5));
			// Container child hboxDestination.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.WidthRequest = 122;
			this.eventbox1.Name = "eventbox1";
			this.hboxDestination.Add(this.eventbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxDestination[this.eventbox1]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 1;
			w18.Expand = false;
			this.vboxDestination.Add(this.hboxDestination);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.hboxDestination]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vboxDestination.Gtk.Box+BoxChild
			this.eventboxSeperator2 = new global::Gtk.EventBox();
			this.eventboxSeperator2.HeightRequest = 1;
			this.eventboxSeperator2.Name = "eventboxSeperator2";
			this.vboxDestination.Add(this.eventboxSeperator2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxDestination[this.eventboxSeperator2]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 2;
			w20.Fill = false;
			this.vboxMainInner.Add(this.vboxDestination);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.vboxDestination]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Padding = ((uint)(5));
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hboxCostPerBlock = new global::Gtk.HBox();
			this.hboxCostPerBlock.Name = "hboxCostPerBlock";
			this.hboxCostPerBlock.BorderWidth = ((uint)(8));
			// Container child hboxCostPerBlock.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 20;
			this.label7.Name = "label7";
			this.hboxCostPerBlock.Add(this.label7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hboxCostPerBlock[this.label7]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hboxCostPerBlock.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Cost to activate:");
			this.hbox12.Add(this.label8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.labelCostPerBlock = new global::Gtk.Label();
			this.labelCostPerBlock.Name = "labelCostPerBlock";
			this.labelCostPerBlock.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.hbox12.Add(this.labelCostPerBlock);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.labelCostPerBlock]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Kalapas / Block");
			this.hbox12.Add(this.label9);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label9]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.hboxCostPerBlock.Add(this.hbox12);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hboxCostPerBlock[this.hbox12]));
			w26.Position = 1;
			this.vboxMainInner.Add(this.hboxCostPerBlock);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hboxCostPerBlock]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 15;
			this.label1.Name = "label1";
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.HBox();
			this.vbox.Name = "vbox";
			this.vbox.Homogeneous = true;
			this.vbox.Spacing = 30;
			this.vbox.BorderWidth = ((uint)(10));
			// Container child vbox.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hboxAmount = new global::Gtk.HBox();
			this.hboxAmount.Name = "hboxAmount";
			this.hboxAmount.Spacing = 6;
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.labelBlocks = new global::Gtk.Label();
			this.labelBlocks.Name = "labelBlocks";
			this.labelBlocks.Xalign = 0F;
			this.labelBlocks.LabelProp = global::Mono.Unix.Catalog.GetString("Blocks:");
			this.hboxAmount.Add(this.labelBlocks);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hboxAmount[this.labelBlocks]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			w29.Padding = ((uint)(7));
			// Container child hboxAmount.Gtk.Box+BoxChild
			this.labelAmountError = new global::Gtk.Label();
			this.labelAmountError.Name = "labelAmountError";
			this.labelAmountError.LabelProp = global::Mono.Unix.Catalog.GetString("Invalid");
			this.hboxAmount.Add(this.labelAmountError);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hboxAmount[this.labelAmountError]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox1.Add(this.hboxAmount);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hboxAmount]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.spinbuttonAmount = new global::Gtk.SpinButton(0D, 1000D, 1D);
			this.spinbuttonAmount.HeightRequest = 35;
			this.spinbuttonAmount.CanFocus = true;
			this.spinbuttonAmount.Name = "spinbuttonAmount";
			this.spinbuttonAmount.Adjustment.PageIncrement = 10D;
			this.spinbuttonAmount.ClimbRate = 1D;
			this.spinbuttonAmount.Numeric = true;
			this.vbox1.Add(this.spinbuttonAmount);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.spinbuttonAmount]));
			w32.Position = 1;
			this.vbox.Add(this.vbox1);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox[this.vbox1]));
			w33.Position = 0;
			// Container child vbox.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hboxAmount1 = new global::Gtk.HBox();
			this.hboxAmount1.Name = "hboxAmount1";
			this.hboxAmount1.Spacing = 6;
			// Container child hboxAmount1.Gtk.Box+BoxChild
			this.labelSelectSecureToken = new global::Gtk.Label();
			this.labelSelectSecureToken.Name = "labelSelectSecureToken";
			this.labelSelectSecureToken.Xalign = 0F;
			this.labelSelectSecureToken.LabelProp = global::Mono.Unix.Catalog.GetString("Secure Token:");
			this.hboxAmount1.Add(this.labelSelectSecureToken);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hboxAmount1[this.labelSelectSecureToken]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			w34.Padding = ((uint)(7));
			// Container child hboxAmount1.Gtk.Box+BoxChild
			this.labelSecureTokenError = new global::Gtk.Label();
			this.labelSecureTokenError.Name = "labelSecureTokenError";
			this.labelSecureTokenError.LabelProp = global::Mono.Unix.Catalog.GetString("Invalid");
			this.hboxAmount1.Add(this.labelSecureTokenError);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hboxAmount1[this.labelSecureTokenError]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox5.Add(this.hboxAmount1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hboxAmount1]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.comboboxAsset = global::Gtk.ComboBox.NewText();
			this.comboboxAsset.HeightRequest = 35;
			this.comboboxAsset.Name = "comboboxAsset";
			this.vbox5.Add(this.comboboxAsset);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.comboboxAsset]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox.Add(this.vbox5);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox[this.vbox5]));
			w38.Position = 1;
			// Container child vbox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hboxAmount2 = new global::Gtk.HBox();
			this.hboxAmount2.Name = "hboxAmount2";
			this.hboxAmount2.Spacing = 6;
			// Container child hboxAmount2.Gtk.Box+BoxChild
			this.labelCostTotal = new global::Gtk.Label();
			this.labelCostTotal.Name = "labelCostTotal";
			this.labelCostTotal.Xalign = 0F;
			this.labelCostTotal.LabelProp = global::Mono.Unix.Catalog.GetString("Total Cost:");
			this.hboxAmount2.Add(this.labelCostTotal);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hboxAmount2[this.labelCostTotal]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			w39.Padding = ((uint)(7));
			this.vbox6.Add(this.hboxAmount2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hboxAmount2]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.labelTotalCost = new global::Gtk.Label();
			this.labelTotalCost.HeightRequest = 40;
			this.labelTotalCost.Name = "labelTotalCost";
			this.labelTotalCost.Xalign = 0F;
			this.vbox6.Add(this.labelTotalCost);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.labelTotalCost]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox.Add(this.vbox6);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox[this.vbox6]));
			w42.Position = 2;
			this.hbox1.Add(this.vbox);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox]));
			w43.Position = 1;
			this.vboxMainInner.Add(this.hbox1);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hbox1]));
			w44.Position = 4;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vboxMainInner.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.BorderWidth = ((uint)(25));
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.Xalign = 1F;
			this.hboxButtons.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.labelStatus]));
			w45.Position = 0;
			w45.Padding = ((uint)(10));
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.hboxSignAndReview = new global::Gtk.HBox();
			this.hboxSignAndReview.Name = "hboxSignAndReview";
			// Container child hboxSignAndReview.Gtk.Box+BoxChild
			this.eventboxActivate = new global::Gtk.EventBox();
			this.eventboxActivate.Name = "eventboxActivate";
			// Container child eventboxActivate.Gtk.Container+ContainerChild
			this.imageActivate = new global::Gtk.Image();
			this.imageActivate.Name = "imageActivate";
			this.imageActivate.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Activate.png");
			this.eventboxActivate.Add(this.imageActivate);
			this.hboxSignAndReview.Add(this.eventboxActivate);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hboxSignAndReview[this.eventboxActivate]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hboxSignAndReview.Gtk.Box+BoxChild
			this.imageActivateDisabled = new global::Gtk.Image();
			this.imageActivateDisabled.Name = "imageActivateDisabled";
			this.imageActivateDisabled.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Activate_disabled.png");
			this.hboxSignAndReview.Add(this.imageActivateDisabled);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hboxSignAndReview[this.imageActivateDisabled]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.hboxButtons.Add(this.hboxSignAndReview);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.hboxSignAndReview]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			this.vboxMainInner.Add(this.hboxButtons);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vboxMainInner[this.hboxButtons]));
			w50.PackType = ((global::Gtk.PackType)(1));
			w50.Position = 5;
			w50.Expand = false;
			w50.Fill = false;
			this.Add(this.vboxMainInner);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
