
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class Wallet
	{
		private global::Gtk.VBox vbox1;
		
		private global::Wallet.ActionBar actionbar;
		
		private global::Wallet.Transactions transactions1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.Wallet
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Wallet.Wallet";
			// Container child Wallet.Wallet.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.actionbar = new global::Wallet.ActionBar ();
			this.actionbar.Events = ((global::Gdk.EventMask)(256));
			this.actionbar.Name = "actionbar";
			this.vbox1.Add (this.actionbar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.actionbar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.transactions1 = new global::Wallet.Transactions ();
			this.transactions1.Events = ((global::Gdk.EventMask)(256));
			this.transactions1.Name = "transactions1";
			this.vbox1.Add (this.transactions1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.transactions1]));
			w2.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
