
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class Wallet
	{
		private global::Wallet.Transactions transactions1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.Wallet
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.Wallet";
			// Container child Wallet.Wallet.Gtk.Container+ContainerChild
			this.transactions1 = new global::Wallet.Transactions();
			this.transactions1.Events = ((global::Gdk.EventMask)(256));
			this.transactions1.Name = "transactions1";
			this.Add(this.transactions1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
