
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class WalletLayout
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.ScrolledWindow scrolledwindow3;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Label labelYourAddress;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Entry entryAddress;

		private global::Gtk.EventBox eventboxCopy;

		private global::Gtk.HBox hboxCopy;

		private global::Gtk.Image imageCopy;

		private global::Gtk.Image imageCopied;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.EventBox eventboxQRCode;

		private global::Gtk.Image image3;

		private global::Gtk.EventBox eventboxCopyPublicKey;

		private global::Gtk.Image image4;

		private global::Gtk.Label labelPublicKeyCopied;

		private global::Gtk.EventBox eventboxSeperator;

		private global::Gtk.HBox hbox2;

		private global::Gtk.EventBox eventboxSend;

		private global::Gtk.Image image5;

		private global::Gtk.Label label4;

		private global::Wallet.WalletReceiveLayout walletreceivelayout1;

		private global::Gtk.Label label6;

		private global::Wallet.WalletSendLayout walletsendlayout1;

		private global::Gtk.Label label8;

		private global::Wallet.WalletSendConfirmationLayout walletsendconfirmationlayout1;

		private global::Gtk.Label label10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.WalletLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.WalletLayout";
			// Container child Wallet.WalletLayout.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.ShowBorder = false;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = true;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			this.vbox8.BorderWidth = ((uint)(30));
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.labelYourAddress = new global::Gtk.Label();
			this.labelYourAddress.Name = "labelYourAddress";
			this.labelYourAddress.LabelProp = global::Mono.Unix.Catalog.GetString("Your Address");
			this.hbox22.Add(this.labelYourAddress);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.labelYourAddress]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(10));
			this.vbox8.Add(this.hbox22);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox22]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.BorderWidth = ((uint)(10));
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryAddress = new global::Gtk.Entry();
			this.entryAddress.HeightRequest = 35;
			this.entryAddress.CanFocus = true;
			this.entryAddress.Name = "entryAddress";
			this.entryAddress.IsEditable = false;
			this.entryAddress.InvisibleChar = '●';
			this.hbox5.Add(this.entryAddress);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryAddress]));
			w4.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.eventboxCopy = new global::Gtk.EventBox();
			this.eventboxCopy.Name = "eventboxCopy";
			// Container child eventboxCopy.Gtk.Container+ContainerChild
			this.hboxCopy = new global::Gtk.HBox();
			this.hboxCopy.Name = "hboxCopy";
			this.hboxCopy.Spacing = 6;
			// Container child hboxCopy.Gtk.Box+BoxChild
			this.imageCopy = new global::Gtk.Image();
			this.imageCopy.Name = "imageCopy";
			this.imageCopy.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Copy.png");
			this.hboxCopy.Add(this.imageCopy);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxCopy[this.imageCopy]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hboxCopy.Gtk.Box+BoxChild
			this.imageCopied = new global::Gtk.Image();
			this.imageCopied.Name = "imageCopied";
			this.imageCopied.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Copied.png");
			this.hboxCopy.Add(this.imageCopied);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxCopy[this.imageCopied]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.eventboxCopy.Add(this.hboxCopy);
			this.hbox5.Add(this.eventboxCopy);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eventboxCopy]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(10));
			this.vbox8.Add(this.hbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox5]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.BorderWidth = ((uint)(10));
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventboxQRCode = new global::Gtk.EventBox();
			this.eventboxQRCode.Name = "eventboxQRCode";
			// Container child eventboxQRCode.Gtk.Container+ContainerChild
			this.image3 = new global::Gtk.Image();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.QRcode.png");
			this.eventboxQRCode.Add(this.image3);
			this.hbox4.Add(this.eventboxQRCode);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventboxQRCode]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.eventboxCopyPublicKey = new global::Gtk.EventBox();
			this.eventboxCopyPublicKey.Name = "eventboxCopyPublicKey";
			// Container child eventboxCopyPublicKey.Gtk.Container+ContainerChild
			this.image4 = new global::Gtk.Image();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.Copy_public_key.png");
			this.eventboxCopyPublicKey.Add(this.image4);
			this.hbox4.Add(this.eventboxCopyPublicKey);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.eventboxCopyPublicKey]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(6));
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelPublicKeyCopied = new global::Gtk.Label();
			this.labelPublicKeyCopied.Name = "labelPublicKeyCopied";
			this.labelPublicKeyCopied.Xalign = 0F;
			this.labelPublicKeyCopied.LabelProp = global::Mono.Unix.Catalog.GetString("Public key copied to clipboard");
			this.hbox4.Add(this.labelPublicKeyCopied);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.labelPublicKeyCopied]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
			w15.Position = 0;
			w15.Expand = false;
			this.vbox8.Add(this.hbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox3]));
			w16.Position = 2;
			w16.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.eventboxSeperator = new global::Gtk.EventBox();
			this.eventboxSeperator.HeightRequest = 1;
			this.eventboxSeperator.Name = "eventboxSeperator";
			this.eventboxSeperator.BorderWidth = ((uint)(10));
			this.vbox8.Add(this.eventboxSeperator);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.eventboxSeperator]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox1.Add(this.vbox8);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox8]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			this.eventbox1.Add(this.vbox1);
			w1.Add(this.eventbox1);
			this.scrolledwindow3.Add(w1);
			this.vbox3.Add(this.scrolledwindow3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow3]));
			w22.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			// Container child hbox2.Gtk.Box+BoxChild
			this.eventboxSend = new global::Gtk.EventBox();
			this.eventboxSend.Name = "eventboxSend";
			// Container child eventboxSend.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.send.png");
			this.eventboxSend.Add(this.image5);
			this.hbox2.Add(this.eventboxSend);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.eventboxSend]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.notebook1.Add(this.vbox3);
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
			this.notebook1.SetTabLabel(this.vbox3, this.label4);
			this.label4.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletreceivelayout1 = new global::Wallet.WalletReceiveLayout();
			this.walletreceivelayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletreceivelayout1.Name = "walletreceivelayout1";
			this.notebook1.Add(this.walletreceivelayout1);
			global::Gtk.Notebook.NotebookChild w27 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.walletreceivelayout1]));
			w27.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("page2");
			this.notebook1.SetTabLabel(this.walletreceivelayout1, this.label6);
			this.label6.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletsendlayout1 = new global::Wallet.WalletSendLayout();
			this.walletsendlayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletsendlayout1.Name = "walletsendlayout1";
			this.notebook1.Add(this.walletsendlayout1);
			global::Gtk.Notebook.NotebookChild w28 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.walletsendlayout1]));
			w28.Position = 2;
			// Notebook tab
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
			this.notebook1.SetTabLabel(this.walletsendlayout1, this.label8);
			this.label8.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletsendconfirmationlayout1 = new global::Wallet.WalletSendConfirmationLayout();
			this.walletsendconfirmationlayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletsendconfirmationlayout1.Name = "walletsendconfirmationlayout1";
			this.notebook1.Add(this.walletsendconfirmationlayout1);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.walletsendconfirmationlayout1]));
			w29.Position = 3;
			// Notebook tab
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("page4");
			this.notebook1.SetTabLabel(this.walletsendconfirmationlayout1, this.label10);
			this.label10.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
