
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class LogSummary
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.LogSummary
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Wallet.LogSummary";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
