
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class SendRaw
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label4;

		private global::Gtk.Label labelHeader;

		private global::Gtk.EventBox eventboxCancel;

		private global::Gtk.Image image5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textviewRawTx;

		private global::Gtk.Label labelStatus;

		private global::Gtk.HBox hbox3;

		private global::Gtk.EventBox eventboxSend;

		private global::Gtk.Image image1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.SendRaw
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.SendRaw";
			// Container child Wallet.SendRaw.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 50;
			this.label4.Name = "label4";
			this.hbox5.Add(this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelHeader = new global::Gtk.Label();
			this.labelHeader.Name = "labelHeader";
			this.labelHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Send Raw Transaction");
			this.hbox5.Add(this.labelHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.labelHeader]));
			w2.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.eventboxCancel = new global::Gtk.EventBox();
			this.eventboxCancel.Name = "eventboxCancel";
			// Container child eventboxCancel.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image();
			this.image5.WidthRequest = 50;
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			this.eventboxCancel.Add(this.image5);
			this.hbox5.Add(this.eventboxCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eventboxCancel]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewRawTx = new global::Gtk.TextView();
			this.textviewRawTx.CanFocus = true;
			this.textviewRawTx.Name = "textviewRawTx";
			this.GtkScrolledWindow.Add(this.textviewRawTx);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelStatus = new global::Gtk.Label();
			this.labelStatus.Name = "labelStatus";
			this.vbox1.Add(this.labelStatus);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelStatus]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.eventboxSend = new global::Gtk.EventBox();
			this.eventboxSend.Name = "eventboxSend";
			this.eventboxSend.VisibleWindow = false;
			// Container child eventboxSend.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Wallet.Assets.misc.send_dialog.png");
			this.eventboxSend.Add(this.image1);
			this.hbox3.Add(this.eventboxSend);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.eventboxSend]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
