
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class WalletLayout
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.ScrolledWindow scrolledwindow3;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Entry entryAddress;

		private global::Gtk.Button buttonCopy;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button buttonQR;

		private global::Gtk.Button buttonKeys;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Button buttonSend;

		private global::Gtk.Label label4;

		private global::Wallet.WalletReceiveLayout walletreceivelayout1;

		private global::Gtk.Label label5;

		private global::Wallet.WalletSendLayout walletsendlayout1;

		private global::Gtk.Label label7;

		private global::Wallet.WalletSendConfirmationLayout walletsendconfirmationlayout1;

		private global::Gtk.Label label9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Wallet.WalletLayout
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Wallet.WalletLayout";
			// Container child Wallet.WalletLayout.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 3;
			this.notebook1.ShowBorder = false;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = true;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Your address:");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 10;
			this.hbox5.BorderWidth = ((uint)(37));
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryAddress = new global::Gtk.Entry();
			this.entryAddress.CanFocus = true;
			this.entryAddress.Name = "entryAddress";
			this.entryAddress.IsEditable = false;
			this.entryAddress.InvisibleChar = '●';
			this.hbox5.Add(this.entryAddress);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryAddress]));
			w3.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.buttonCopy = new global::Gtk.Button();
			this.buttonCopy.WidthRequest = 65;
			this.buttonCopy.CanFocus = true;
			this.buttonCopy.Name = "buttonCopy";
			this.buttonCopy.UseUnderline = true;
			this.buttonCopy.Label = global::Mono.Unix.Catalog.GetString("Copy");
			this.hbox5.Add(this.buttonCopy);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonCopy]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonQR = new global::Gtk.Button();
			this.buttonQR.WidthRequest = 120;
			this.buttonQR.HeightRequest = 50;
			this.buttonQR.CanFocus = true;
			this.buttonQR.Name = "buttonQR";
			this.buttonQR.UseUnderline = true;
			this.buttonQR.Label = global::Mono.Unix.Catalog.GetString("QRCode");
			this.hbox4.Add(this.buttonQR);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonQR]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonKeys = new global::Gtk.Button();
			this.buttonKeys.WidthRequest = 120;
			this.buttonKeys.HeightRequest = 50;
			this.buttonKeys.CanFocus = true;
			this.buttonKeys.Name = "buttonKeys";
			this.buttonKeys.UseUnderline = true;
			this.buttonKeys.Label = global::Mono.Unix.Catalog.GetString("keys");
			this.hbox4.Add(this.buttonKeys);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonKeys]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.eventbox1.Add(this.vbox1);
			w1.Add(this.eventbox1);
			this.scrolledwindow3.Add(w1);
			this.vbox3.Add(this.scrolledwindow3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow3]));
			w13.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonSend = new global::Gtk.Button();
			this.buttonSend.WidthRequest = 120;
			this.buttonSend.HeightRequest = 50;
			this.buttonSend.CanFocus = true;
			this.buttonSend.Name = "buttonSend";
			this.buttonSend.UseUnderline = true;
			this.buttonSend.Label = global::Mono.Unix.Catalog.GetString("Send");
			this.vbox2.Add(this.buttonSend);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonSend]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox2.Add(this.vbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w16.Position = 1;
			this.notebook1.Add(this.vbox3);
			// Notebook tab
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
			this.notebook1.SetTabLabel(this.vbox3, this.label4);
			this.label4.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletreceivelayout1 = new global::Wallet.WalletReceiveLayout();
			this.walletreceivelayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletreceivelayout1.Name = "walletreceivelayout1";
			this.notebook1.Add(this.walletreceivelayout1);
			global::Gtk.Notebook.NotebookChild w18 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.walletreceivelayout1]));
			w18.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("page2");
			this.notebook1.SetTabLabel(this.walletreceivelayout1, this.label5);
			this.label5.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletsendlayout1 = new global::Wallet.WalletSendLayout();
			this.walletsendlayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletsendlayout1.Name = "walletsendlayout1";
			this.notebook1.Add(this.walletsendlayout1);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.walletsendlayout1]));
			w19.Position = 2;
			// Notebook tab
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
			this.notebook1.SetTabLabel(this.walletsendlayout1, this.label7);
			this.label7.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.walletsendconfirmationlayout1 = new global::Wallet.WalletSendConfirmationLayout();
			this.walletsendconfirmationlayout1.Events = ((global::Gdk.EventMask)(256));
			this.walletsendconfirmationlayout1.Name = "walletsendconfirmationlayout1";
			this.notebook1.Add(this.walletsendconfirmationlayout1);
			global::Gtk.Notebook.NotebookChild w20 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.walletsendconfirmationlayout1]));
			w20.Position = 3;
			// Notebook tab
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("page4");
			this.notebook1.SetTabLabel(this.walletsendconfirmationlayout1, this.label9);
			this.label9.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
