
// This file has been generated by the GUI designer. Do not modify.
namespace Wallet
{
	public partial class VerticalMenu
	{
		private global::Gtk.VBox vbox3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Wallet.VerticalMenu
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Wallet.VerticalMenu";
			// Container child Wallet.VerticalMenu.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
