
// This file has been generated by the GUI designer. Do not modify.
namespace NodeTester
{
	public partial class AddressManagerEditorWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action ActionAction;

		private global::Gtk.Action AddAction;

		private global::Gtk.Action SaveAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeviewAddresses;

		private global::Gtk.Toolbar toolbar1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NodeTester.AddressManagerEditorWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.ActionAction = new global::Gtk.Action("ActionAction", global::Mono.Unix.Catalog.GetString("Action"), null, null);
			this.ActionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Action");
			w1.Add(this.ActionAction, null);
			this.AddAction = new global::Gtk.Action("AddAction", global::Mono.Unix.Catalog.GetString("Add"), null, null);
			this.AddAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Add");
			w1.Add(this.AddAction, null);
			this.SaveAction = new global::Gtk.Action("SaveAction", global::Mono.Unix.Catalog.GetString("Save"), null, null);
			this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
			w1.Add(this.SaveAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "NodeTester.AddressManagerEditorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Address Manager Editor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NodeTester.AddressManagerEditorWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='ActionAction' action='ActionAction'><menuitem name='AddAction' action='AddAction'/><menuitem name='SaveAction' action='SaveAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewAddresses = new global::Gtk.TreeView();
			this.treeviewAddresses.CanFocus = true;
			this.treeviewAddresses.Name = "treeviewAddresses";
			this.GtkScrolledWindow.Add(this.treeviewAddresses);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'/></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.AddAction.Activated += new global::System.EventHandler(this.Menu_Add);
			this.SaveAction.Activated += new global::System.EventHandler(this.Menu_Save);
		}
	}
}
